name: cicd

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 

jobs: 
  cicd: 
    runs-on: ubuntu-latest

    steps: 
    - name: checkout
      uses: actions/checkout@v4

    - name: Lint Code Base
      uses: super-linter/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.VANSH_TOKEN }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis    
      uses: github/codeql-action/analyze@v2
      with:
        upload: False
        output: sarif-results

    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '11'
        
    - name: build the code
      run: mvn clean package
      
    - name: run unit test 
      run: mvn test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build docker image
      run: docker build -t vansh2222/vanshverticurl .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          push: true
          tags: vansh2222/vanshverticurl:latest

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: 'https://www.zaproxy.org/'
       
